### ISSUE TITLE
doesn't initialize with rgb .tif file

### ISSUE THREAD

**Issue by aliWilkening** [ckarfusehr/gelpy#2]
It worked once I fixed my tif and made it grayscale with imageJ. Just leaving here so people silly like me can figure it out :)

Hi! I'm not very experienced with this package using stuff so sorry if this is just a me thing. 
I'm trying to use the example notebook as a framework to start my analysis but setup_gel method doesn't work with my .tif

I think its because my tifs are in RBG colorspace while both the examples are in Gray colorspace (according to the "information" provided in finder). I'm not sure if I should change it in Fiji or something or if there's a way to make gelpy accept the rbg color information.

Here's the error trace if that's helpful:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[14], line 13
      6 #gel.setup_gel()
      7 #gel.show_adjusted_images(save_adjusted_gels="test123.jpg")
      8 
      9 # gel.setup_gel(x_label_pos=(150, 4480, 20), 
     10 #               remove_bg=True)           #, line_profile_width=150)
     12 labels = ["scaffold", "2 MgCl₂, 500 NaCl","4 MgCl₂, 500 NaCl","6 MgCl₂, 500 NaCl","8 MgCl₂, 500 NaCl","10 MgCl₂, 500 NaCl","150 NaCl","300 NaCl","400 NaCl","500 NaCl","600 NaCl", "700 NaCl","6 MgCl₂","10 MgCl₂","6 MgCl₂, 150 NaCl,1/2 scaf","10 MgCl₂, 150 NaCl,1/2 scaf","6 MgCl₂, 300 NaCl,1/2 scaf","10 MgCl₂, 300 NaCl,1/2 scaf","6 MgCl₂, 500 NaCl,1/2 scaf"," 10 MgCl₂, 500 NaCl,1/2 scaf"]
---> 13 gel.setup_gel(labels=labels, x_label_pos=(150, 4485, 20),
     14               label_rotation=90,
     15               line_profile_width=180,
     16               remove_bg=True,
     17               img_height_factor=1) # increase if labels and titles are overlapping
     18 gel.show_adjusted_images()

File /opt/anaconda3/lib/python3.8/site-packages/gelpy/package_api.py:71, in Gel.setup_gel(self, labels, x_label_pos, gamma, gain, intensity_range, img_height_factor, label_rotation, save, show_type, line_profile_width, remove_bg, bg_model, bg_model_input)
     40 def setup_gel(self, labels=None, x_label_pos=None, gamma=DEFAULT_GAMMA, gain=DEFAULT_GAIN, 
     41               intensity_range=DEFAULT_INTENSITY_RANGE, img_height_factor=DEFAULT_IMG_HEIGHT_FACTOR, 
     42               label_rotation=DEFAULT_LABEL_ROTATION, save=False, 
     43               show_type=DEFAULT_SHOW_TYPE, line_profile_width=None,
     44                 remove_bg=False, bg_model=MODEL_2D_PLANE_FIT_NAME, bg_model_input=None):
     45     """
     46     Initializes the gel instance by loading the image, adjusting its properties and optionally 
     47     removing its background.
   (...)
     68         ValueError: If an invalid fit type is provided.
     69     """
---> 71     self.init_image(labels, x_label_pos, gamma, gain, intensity_range, img_height_factor, label_rotation)
     73     self.plot_and_adjust_gels(show_type)
     74     self.setup_line_profile(line_profile_width)

File /opt/anaconda3/lib/python3.8/site-packages/gelpy/package_api.py:112, in Gel.init_image(self, labels, x_label_pos, gamma, gain, intensity_range, img_height_factor, label_rotation)
     99 def init_image(self, labels, x_label_pos, gamma, gain, intensity_range, img_height_factor, label_rotation):
    100     """
    101     Initializes the gel image with the provided parameters.
    102 
   (...)
    110         label_rotation (int): The rotation angle of the labels.
    111     """
--> 112     self.Image = Image(self.image, self.file_name_without_ext, labels, x_label_pos, label_rotation,
    113                        img_height_factor=img_height_factor, gamma=gamma, gain=gain, intensity_range=intensity_range)
    114     self.labels = self.Image.labels
    115     self.x_label_pos = x_label_pos

File /opt/anaconda3/lib/python3.8/site-packages/gelpy/image_handling.py:33, in Image.__init__(self, image, file_name_withou_extension, labels, x_label_pos, label_rotation, img_height_factor, gamma, gain, intensity_range)
     31 # Attributes
     32 self.gel_image = image
---> 33 self.image_height, self.image_width  = self.gel_image.shape
     34 self.file_name_without_extension = file_name_withou_extension
     35 self.labels = labels

ValueError: too many values to unpack (expected 2)

**Comment by ckarfusehr** [comment]
Hi aliWilkening, 

I know it is too late and not useful anymore, but I just updated the code to allow RGB files. You were right about the problem. I also decided to deprecate this package, as I do not have the time to maintain it.

All the best with your future gels,
Christoph
